name: "ChainAlert"

on:
  push:
    branches: [master]

jobs:
  chainalert:
    name: ChainAlert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: checkmarx/chainalert-github-action@master
